apiVersion: v1
kind: Service
metadata:
  name: opsknight-service
  namespace: opsknight
  labels:
    app: opsknight-app
spec:
  selector:
    app: opsknight-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
  type: ClusterIP
