apiVersion: v1
kind: Service
metadata:
  name: opssentinal-service
  namespace: opssentinal
  labels:
    app: opssentinal-app
spec:
  selector:
    app: opssentinal-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
  type: ClusterIP
