# Example values for GCE Ingress
ingress:
  enabled: true
  className: gce
  annotations:
    kubernetes.io/ingress.global-static-ip-name: opssentinal-ip
    networking.gke.io/managed-certificates: opssentinal-cert
  hosts:
    - host: opssentinal.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
