apiVersion: v2
name: opssentinal
description: Professional Open-Source Incident Management Platform for SREs and DevOps teams
type: application
version: 1.0.0
appVersion: '1.0.0'
home: https://github.com/dushyant-rahangdale/opssentinal
sources:
  - https://github.com/dushyant-rahangdale/opssentinal
keywords:
  - incident-management
  - on-call
  - sre
  - devops
  - monitoring
maintainers:
  - name: Dushyant Rahangdale
    url: https://github.com/dushyant-rahangdale
icon: https://raw.githubusercontent.com/dushyant-rahangdale/opssentinal/main/public/logo.png
