apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsknight.fullname" . }}-secrets
  labels:
    {{- include "opsknight.labels" . | nindent 4 }}
type: Opaque
data:
  NEXTAUTH_SECRET: {{ .Values.secrets.nextauthSecret | b64enc | quote }}
  CRON_SECRET: {{ .Values.secrets.cronSecret | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgresql.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | b64enc | quote }}
