apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opssentinal.fullname" . }}-config
  labels:
    {{- include "opssentinal.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  NEXTAUTH_URL: {{ .Values.config.nextauthUrl | quote }}
  PORT: {{ .Values.config.port | quote }}
  HOSTNAME: {{ .Values.config.hostname | quote }}
  NEXT_TELEMETRY_DISABLED: {{ .Values.config.nextTelemetryDisabled | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  {{- if .Values.postgresql.enabled }}
  POSTGRES_HOST: {{ printf "%s-postgresql" (include "opssentinal.fullname" .) | quote }}
  {{- else }}
  POSTGRES_HOST: {{ .Values.postgresql.host | quote }}
  {{- end }}
  POSTGRES_PORT: {{ .Values.postgresql.port | quote }}
